<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="mobile-web-app-capable" content="yes">
    <title><?= K_PRODUCT_NAME ?> - <?= $title ?></title>

    <link href="<?=K_BASE_URL?>/css/style.css" rel="stylesheet">
    <script src="/javascript/jquery/jquery.min.js"></script>
    <script src="/javascript/jquery-ui/jquery-ui.min.js"></script>
    <script src="/javascript/underscore/underscore.min.js"></script>
    <script src="/javascript/typeahead.js/typeahead.jquery.min.js"></script>
    <script src="/javascript/bootstrap/js/bootstrap.min.js"></script>

    <link rel="icon" href="<?=K_BASE_URL?>/img/favicon.png" type="image/png">
  </head>

  <body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" href="<?=K_BASE_URL?>">
            <img src="<?=K_LOGO_URL?>" alt="logo">
          </a>
        </div>
      </div>
    </nav>
<?php
    require($viewFileName);
?>
    <footer class="footer">
      <a href="<?=K_BASE_URL?>/index/privacy"><?=_("Datenschutz")?></a> |
      <a href="<?=K_BASE_URL?>/index/imprint"><?=_("Impressum")?></a>
    </footer>
  </body>
</html>
