<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="mobile-web-app-capable" content="yes">
    <title><?= K_PRODUCT_NAME ?> - <?= $title ?></title>

    <link href="<?=K_BASE_URL?>/css/style.css" rel="stylesheet">
    <script src="/javascript/jquery/jquery.min.js"></script>
    <script src="/javascript/jquery-ui/jquery-ui.min.js"></script>
<!--    <link href="/javascript/jquery-ui/css/smoothness/jquery-ui.min.css" rel="stylesheet" type="text/css">
    <script src="/javascript/jquery-ui-touch-punch/jquery.ui.touch-punch.min.js"></script> -->
    <script src="/javascript/underscore/underscore.min.js"></script>
    <script src="/javascript/typeahead.js/typeahead.jquery.min.js"></script>
    <script src="/javascript/bootstrap/js/bootstrap.min.js"></script>
<!--    <link rel="stylesheet" href="/js/bootstrap-multiselect.css">
    <script src="/js/bootstrap-multiselect.min.js"></script> -->
    <script src="/javascript/moment/moment-with-locales.min.js"></script>
    <script src="/javascript/eonasdan-bootstrap-datetimepicker/bootstrap-datetimepicker.min.js"></script>
    <link href="/javascript/eonasdan-bootstrap-datetimepicker/bootstrap-datetimepicker.min.css" rel="stylesheet">

<!--    <script src="/js/tools.js"></script> -->
<!--    <link rel="icon" href="<?=K_BASE_URL?>/img/favicon.png" type="image/png"> -->
<!--    <link rel="icon" href="/img/Logo192.png" sizes="192x192"> -->
  </head>

  <body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="<?=K_BASE_URL?>">
            <img src="<?=K_BASE_URL?>/img/Logo.svg" onerror="this.onerror=null; this.src='<?=K_BASE_URL?>/img/Logo.png'" alt="logo">
          </a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><a href="<?=K_BASE_URL?>/orderday"><?= _("Bestellungen") ?></a></li>
          </ul>
          <ul class="nav navbar-nav">
            <li><a href="<?=K_BASE_URL?>/payment"><?= _("Bezahlungen") ?></a></li>
          </ul>
          <ul class="nav navbar-nav">
            <li><a href="<?=K_BASE_URL?>/account"><?= _("Konto") ?></a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><a href="<?=K_BASE_URL?>/index/logout"><span class="glyphicon glyphicon-log-out"></span> <?= _("Abmelden") ?></a></li>
          </ul>
        </div>
      </div>
    </nav>
<?php
    require($viewFileName);
?>
    <footer class="footer">
<!--      <a class="footer-brand pull-left" href="//ld-didactic.de">
        <img src="<?=K_BASE_URL?>/img/LeyboldDidactic.svg">
      </a> -->
      <a href="<?=K_BASE_URL?>/index/privacy"><?=_("Datenschutz")?></a> |
      <a href="<?=K_BASE_URL?>/index/imprint"><?=_("Impressum")?></a>
    </footer>
  </body>
</html>
