<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="mobile-web-app-capable" content="yes">
    <title><?= K_PRODUCT_NAME ?> - <?= $title ?></title>

    <link href="<?=K_BASE_URL?>/css/style.css" rel="stylesheet">
    <script src="/javascript/jquery/jquery.min.js"></script>
    <script src="/javascript/jquery-ui/jquery-ui.min.js"></script>
    <script src="/javascript/underscore/underscore.min.js"></script>
<!--    <script src="/javascript/typeahead.js/typeahead.jquery.min.js"></script> -->
    <script src="/javascript/bootstrap/js/bootstrap.min.js"></script>
    <script src="/javascript/moment/moment-with-locales.min.js"></script>
    <script src="/javascript/eonasdan-bootstrap-datetimepicker/bootstrap-datetimepicker.min.js"></script>
    <link href="/javascript/eonasdan-bootstrap-datetimepicker/bootstrap-datetimepicker.min.css" rel="stylesheet">
  </head>

  <body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="<?=K_BASE_URL?>">
            <img src="<?=K_LOGO_URL?>" alt="logo">
          </a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><a href="<?=K_BASE_URL?>/orderday"><span class="glyphicon glyphicon-shopping-cart"></span> <?= _("Bestellungen") ?></a></li>
            <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
              <span class="glyphicon glyphicon-eur"></span> <?= _("Zahlungen") ?><span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="<?=K_BASE_URL?>/payment">Übersicht</a></li>
                <li><a href="<?=K_BASE_URL?>/payment/open">Offen</a></li>
                <li role="separator" class="divider"></li>
                <li><a href="<?=K_BASE_URL?>/payment/add">Erfassen</a></li>
              </ul>
            </li>
            <li><a href="<?=K_BASE_URL?>/upload"><span class="glyphicon glyphicon-file"></span> Dateien</a></li>
            <li><a href="<?=K_BASE_URL?>/statistic"><span class="glyphicon glyphicon-stats"></span> <?= _("Statistik") ?></a></li>
            <li><a href="<?=K_BASE_URL?>/settings"><span class="glyphicon glyphicon-cog"></span> <?= _("Einstellungen") ?></a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><a href="<?=K_BASE_URL?>/index/logout"><span class="glyphicon glyphicon-log-out"></span> <?= _("Abmelden") ?></a></li>
          </ul>
        </div>
      </div>
    </nav>
<?php
    require($viewFileName);
?>
    <footer class="footer">
<!--      <a href="<?=K_BASE_URL?>/index/privacy"><?=_("Datenschutz")?></a> |
      <a href="<?=K_BASE_URL?>/index/imprint"><?=_("Impressum")?></a> -->
      <a href="https://github.com/kkoop/pizza" target="_blank">Source</a> |
      <a href="https://github.com/kkoop/pizza/issues" target="_blank">Bugtracker</a>
    </footer>
  </body>
</html>
