<?php
if (isset($successMessage)) {
  printf('<div class="alert alert-success">%s</div>', $successMessage);
  echo('<script>setTimeout(function(){ window.location="'.K_BASE_URL.'"; }, 1000);</script>');
  return;
}
?>
<div class="container">
  <div class="col-md-6">
    <h2>Zahlungen erfassen</h2>
    <form method="post">
      <div id="tblPayments">
      </div>
      <div class="row form-group">
        <div class="col-xs-2">
          <button class="btn btn-primary">Speichern</button>
        </div>
      </div>
    </form>
  </div>
  
  <div class="col-md-6">
<?php 
    if (count($debts)): ?>
    <h2>Zu zahlen</h2>
<?php
    foreach ($debts as $debt): ?>
    <div class="row">
      <label class="col-xs-8 col-md-4 control-label"><?=htmlspecialchars($debt['name'])?></label>
      <label class="col-xs-4 col-md-2 control-label"><?=sprintf("%.2f", $debt['amount'])?> €</label>
    </div>
<?php 
    endforeach; 
    endif; ?>
  </div>
</div>

<script>
function checkNeededRows() {
  var $table = $("#tblPayments");
  var $lastRow = $table.find(".row:last-child");
  if ($lastRow.length == 0 || $lastRow.find("input[name='amount[]']").val()!='') {
    var $newRow = $(`<div class="row form-group">
        <div class="col-xs-8">
          <label class="control-label">Von:</label>
          <select class="form-control" name="user[]"><option value=""></option>
<?php
            foreach ($users as $user) {
              printf('<option value="%d">%s</option>', $user->id, $user->name);
            }
?>
          </select>
        </div>
        <div class="col-xs-4">
          <label class="control-label">Betrag:</label>
          <div class="input-group">
            <input type="number" min="0.01" step="0.01" max="100" class="form-control" name="amount[]">
            <span class="input-group-addon">€</label>
          </div>
        </div>
      </div>`);
    $table.append($newRow);
  }
}
$("#tblPayments").on("keyup","input",checkNeededRows);
checkNeededRows();
</script>
