<div class="container">

  <div class="panel panel-default">
    <div class="panel-heading">
      <form class="form-inline" method="get">
        <h4>Zahlungen für den Zeitraum von <input type="date" class="form-control" name="startDate" value="<?=$startDate?>" size="10">
        bis <input type="date" class="form-control" name="endDate" value="<?=$endDate?>" size="10">
        <button type="submit" class="btn btn-default">Aktualisieren</button></h4>
      </form>
    </div>
    
    <div class="panel-body">
      <h2>Zahlungen</h2>
      <table class="table table-striped">
        <thead><tr><th>Datum</th><th>Von</th><th>An</th><th class="currency">Betrag</th></tr></thead>
        <tbody>
<?php   
        foreach ($payments as $payment) {
          printf('<tr><td>%s</td><td>%s</td><td>%s</td><td class="currency">%.2f €</td></tr>',
            \Pizza\Library\DateTimeFormatter::DateFormatter()->format($payment->time),
            htmlspecialchars($payment->fromName),
            htmlspecialchars($payment->toName),
            $payment->amount);
        }
?>
      </tbody>
      </table>
      
      <h2>Summe der Zahlungen zwischen Benutzern</h2>
      <table class="table">
        <thead><tr><th/>
<?php     foreach ($paymentMatrix as $id=>$column)
            printf('<th>%s</th>', htmlspecialchars($userMap[$id])); ?>
        </tr></thead>
<?php     foreach ($paymentMatrix as $id=>$row) { 
            printf('<tr><th>%s</th>', $userMap[$id]);
            foreach ($row as $user=>$amount)
              if ($user != $id)
                printf('<td %s>%.2f €</td>', $amount==0 ? 'class="text-muted"' : "", $amount);
              else
                echo('<td/>');
            echo('</tr>');
          } ?>
      </table>
      
      <h2>Summe der zu bezahlenden Bestellungen zwischen Benutzern</h2>
      <table class="table">
        <thead><tr><th/>
<?php     foreach ($orderMatrix as $id=>$column)
            printf('<th>%s</th>', htmlspecialchars($userMap[$id])); ?>
        </tr></thead>
<?php     foreach ($orderMatrix as $id=>$row) { 
            printf('<tr><th>%s</th>', $userMap[$id]);
            foreach ($row as $user=>$amount)
              if ($user != $id)
                printf('<td %s>%.2f €</td>', $amount==0 ? 'class="text-muted"' : "", $amount);
              else
                echo('<td/>');
            echo('</tr>');
          } ?>
      </table>
      
      <h2>Offene Beträge zwischen Benutzern</h2>
      <small>Negative Beträge sind Schulden, positive Beträge Guthaben</small>
      <table class="table">
        <thead><tr><th/>
<?php     foreach ($userMap as $user=>$name)
            printf('<th>%s</th>', htmlspecialchars($name)); ?>
        </tr></thead>
<?php     foreach ($userMap as $user1=>$name1) { 
            printf('<tr><th>%s</th>', $name1);
            foreach ($userMap  as $user2=>$name2)
              if ($user1 != $user2) {
                $diff = $paymentMatrix[$user1][$user2] - $orderMatrix[$user1][$user2]
                  - $paymentMatrix[$user2][$user1] + $orderMatrix[$user2][$user1];
                printf('<td class="%s">%.2f €</td>', abs($diff)<0.01 ? 'text-muted' : ($diff < 0 ? 'negative' : 'positive'), $diff);
              } else {
                echo('<td/>');
              }
            echo('</tr>');
          } ?>
      </table>
    </div>
  </div>
</div>
