<?php
if (isset($successMessage)) {
  printf('<div class="alert alert-success">%s</div>', $successMessage);
  return;
}
?>
<div class="container">
  <h2>Zahlung erfassen</h2>
  <form class="form-horizontal" method="post">
    <div class="row form-group">
      <label class="col-sm-3 control-label">Von:</label>
      <div class="col-sm-8">
        <select class="form-control" name="user" required><option value=""></option>
<?php
          foreach ($users as $user) {
            printf('<option value="%d">%s</option>', $user->id, $user->name);
          }
?>
        </select>
      </div>
    </div>
    <div class="row form-group">
      <label class="col-sm-3 control-label">Betrag:</label>
      <div class="col-sm-3 col-md-2">
        <div class="input-group">
          <input type="number" min="0.01" step="0.01" max="100" class="form-control" name="amount" required>
          <span class="input-group-addon">€</label>
        </div>
      </div>
    </div>
    <div class="row form-group">
      <div class="col-sm-offset-3 col-md-offset-2 col-sm-2">
        <button class="btn btn-primary">Speichern</button>
      </div>
    </div>
  </form>
</div>
