<style>
td.negative {
  color: red;
}
</style>

<div class="container">

  <div class="panel panel-default">
    <div class="panel-heading">
      <form class="form-inline">
        <h4>Zahlungen für den Zeitraum von <input type="text" class="form-control" name="startDate" value="<?=$startDate?>" size="10">
        bis <input type="text" class="form-control" name="startDate" value="<?=$endDate?>" size="10">
        <button type="submit" class="btn btn-default">Aktualisieren</button></h4>
      </form>
    </div>
    
    <div class="panel-body">
      <table class="table table-striped">
        <tr><th>Datum</th><th>Von</th><th>An</th><th>Betrag</th></tr>
<?php   
        foreach ($payments as $payment) {
          printf('<tr><td>%s</td><td>%s</td><td>%s</td><td class="%s">%s €</td></tr>',
            strftime("%x", $payment->time),
            $payment->fromName,
            $payment->toName,
            $payment->toId == $_SESSION['user']->id ? "positive" : "negative",
            $payment->amount);
        }
?>
      </table>
      <a href="<?=K_BASE_URL?>/payment/edit" class="btn btn-primary">Erhaltene Zahlung eintragen</a>
    </div>
  </div>
</div>
