<div class="container">

  <div class="panel panel-default">
    <div class="panel-heading">
      <form class="form-inline" method="get">
        <h4>Zahlungen für den Zeitraum von <input type="date" class="form-control" name="startDate" value="<?=$startDate?>" size="10">
        bis <input type="date" class="form-control" name="endDate" value="<?=$endDate?>" size="10">
        <button type="submit" class="btn btn-default">Aktualisieren</button></h4>
      </form>
    </div>
    
    <div class="panel-body">
      <table class="table table-striped">
        <thead><tr><th>Datum</th><th>Von</th><th>An</th><th class="currency">Betrag</th></tr></thead>
        <tbody>
<?php   
        foreach ($transactions as $transaction) {
          if (get_class($transaction) == "Pizza\Model\Payment") {
            printf('<tr><td>%s</td><td>%s</td><td>%s</td><td class="currency %s">%.2f €</td></tr>',
              \Pizza\Library\DateTimeFormatter::DateFormatter()->format($transaction->time),
              htmlspecialchars($transaction->fromName),
              htmlspecialchars($transaction->toName),
              $transaction->toId == $_SESSION['user']->id ? "positive" : "negative",
              $transaction->amount);
          } else {
            printf('<tr><td>%s</td><td>%s</td><td>%s</td><td class="currency %s">%.2f €</td></tr>',
              \Pizza\Library\DateTimeFormatter::DateFormatter()->format($transaction->time),
              htmlspecialchars($_SESSION['user']->name),
              htmlspecialchars($transaction->deliveryservice),
              "negative",
              $transaction->amount);
          }
        }
?>
      </tbody>
      <tfooter>
        <tr><td colspan="3"></td><td class="currency <?=$balance < 0 ? "negative" : ""?>"><?=sprintf("%.2f €", $balance)?></td></tr>
      </tfooter>
      </table>
      <a href="<?=K_BASE_URL?>/payment/add" class="btn btn-primary">Erhaltene Zahlungen eintragen</a>
    </div>
  </div>
</div>
