<div class="container">
  <h1>Bestelltag bearbeiten</h1>
  <form class="form-horizontal" action="<?=K_BASE_URL?>/orderday/edit" method="post">
    <input type="hidden" name="id" value="<?=$day->id?>">
    <div class="form-group row">
      <label class="col-sm-2 control-label">Bestellzeit:</label>
<!--      <div class="col-sm-4"><input type="datetime-local" class="form-control" name="time"></div>-->
      <div class="col-sm-4"><input type="text" id="inputTime" class="form-control" name="time" value="<?=strftime("%x %X", $day->time)?>" required></div>
    </div>
    <div class="form-group row">
      <label class="col-sm-2 control-label">Lieferdienst:</label>
      <div class="col-sm-4"><input type="text" class="form-control" name="deliveryService" value="<?=htmlspecialchars($day->deliveryservice)?>" required></div>
      <label class="col-sm-1 control-label">URL:</label>
      <div class="col-sm-5"><input type="text" class="form-control" name="deliveryServiceUrl" value="<?=htmlspecialchars($day->url)?>"></div>
    </div>
    <div class="form-group row">
      <label class="col-sm-2 control-label">Organisator:</label>
      <div class="col-sm-4"><select class="form-control" name="organizer">
<?php
        foreach ($users as $user) {
          printf('<option value="%d" %s>%s</option>', $user->id, $user->id==$day->organizer ? "selected" : "", htmlspecialchars($user->name));
        }
?>
      </select></div>
    </div>
    <div class="row">
      <div class="col-sm-4 col-sm-offset-2"><button type="submit" class="btn btn-primary">Speichern</button></div>
    </div>
  </form>
</div>

<script>
moment.locale('de_DE.utf8');
$("#inputTime").datetimepicker({
  locale: 'de',
  format: 'L LT',
  minDate: moment()
});
$(function() { $("#inputTime").data("DateTimePicker").date(moment().hours(11).minutes(30)); });
$("form").submit(function(e) {
  $("#inputTime").data("DateTimePicker").format('YYYY-MM-DD HH:mm');
});
</script>
