<div class="container">

  <h2>Offene Bestellungen</h2>
  <ul class="list-group">
<?php foreach ($openOrderDays as $order) : ?>
    <li class="list-group-item">
      <a href="<?=$baseUrl?>/orderday/view/?id=<?=$order->id?>">
        <?= strftime("%x %X", $order->time) ?> - <?= $order->deliveryservice ?>
      </a> 
      <span class="badge"><?=$order->orderCount?></span>
    </li>
<?php endforeach; ?>
    <li class="list-group-item"><a href="<?=$baseUrl?>/orderday/new" class="btn btn-primary">Neu</button></a>
  </ul>

<?php if (!empty($pastOrderDays)): ?>
  <h2>Abgeschlossene Bestellungen</h2>
  <ul class="list-group">
<?php foreach ($pastOrderDays as $order): ?>
    <li class="list-group-item">
      <a href="<?=$baseUrl?>/orderday/view/?id=<?=$order->id?>"><?= strftime("%x %X", $order->time) ?></a> 
      <span class="badge"><?=$order->orderCount?></span>
    </li>
<?php endforeach; ?>
  </ul>
<?php endif; ?>
  
</div>
