<div class="container">
  <h1>Neuer Bestelltag</h1>
  <form class="form-horizontal" action="." method="post">
    <div class="row">
      <label class="col-sm-2 control-label">Bestellzeit</label>
      <div class="col-sm-4"><input type="datetime-local" class="form-control" name="time"></div>
    </div>
    <div class="row">
      <label class="col-sm-2 control-label">Kommentar</label>
      <div class="col-sm-4"><input type="text" class="form-control" name="comment"></div>
    </div>
  </form>
</div>
