<div class="container" id="divMain">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3>Bestellungen <?=strftime("%x %X", $orderday->time)?>
<?php if ($showBtnEdit): ?>
        <a href="<?=K_BASE_URL?>/orderday/edit/?id=<?=$orderday->id?>" class="pull-right"><span class="glyphicon glyphicon-pencil"></span></a>
<?php endif; ?>
      </h3>
      <div class="row">
        <label class="col-sm-2 col-xs-4 control-label">Organisator:</label>
        <div class="col-sm-4 col-xs-8"><?=htmlspecialchars($orderday->getOrganizer()->name)?></div>
        <div class="clearfix visible-xs-block"></div>
        <label class="col-sm-2 col-xs-4 control-label">Lieferdienst:</label>
        <div class="col-sm-4 col-xs-8">
          <?php if (!empty($orderday->url))
            printf('<a href="%s" target="_blank">%s</a>', $orderday->url, htmlspecialchars($orderday->deliveryservice));
          else
            echo(htmlspecialchars($orderday->deliveryservice));
          ?>
        </div>
      </div>
    </div>
    <div class="panel-body">
      <ul class="list-group">
<?php 
      $ownOrder = false;
      $sum = 0.0;
      foreach ($orders as $order) {
        if ($orderday->organizer == $_SESSION['user']->id || ($order->getUser()->id == $_SESSION['user']->id && $orderday->time > time())) {
          $ownOrder = true;
          $editLink = sprintf('<a href="%s/order/edit/?id=%d"><span class="glyphicon glyphicon-pencil"></span></a>',
            K_BASE_URL,
            $order->id);
        } else {
          $editLink = '';
        }
        printf('<li class="list-group-item"><label>%s</label>: %s <i>%s</i><span class="badge">%.2f €</span>%s</li>',
          htmlspecialchars($order->getUser()->name),
          htmlspecialchars($order->product),
          !empty($order->comment) ? '('.htmlspecialchars($order->comment).')' : '',
          $order->price,
          $editLink);
        $sum += $order->price;
      }
      if ($showBtnAdd) {
        printf('<li class="list-group-item"><a href="%s/order/edit/?day=%d" id="lnkAddOrder" class="btn btn-primary">Bestellung hinzufügen</a></li>',
          K_BASE_URL,
          $orderday->id);
      }
?>
      </ul>
<?php if ($showBtnOrderReady): ?>
        <button class="btn btn-primary" id="btnOrderReady">Essen ist da</button>
<?php endif; ?>
    </div>
    <div class="panel-footer">
      <?= sprintf("Insgesamt %d Bestellungen, %.2f €", count($orders), $sum) ?>
    </div>
  </div>
  
</div>

<script>
<?php if ($ownOrder): ?>
$("#lnkAddOrder").click(function(e) {
  return confirm("Sie haben schon etwas bestellt. Möchten Sie trotzdem eine weitere Bestellung hinzufügen?");
});
<?php endif; ?>
$("#btnOrderReady").click(function(e) {
  $(this).prop("disabled", "true");
  $(this).text("Sende E-Mails...");
  $('<span class="glyphicon glyphicon-refresh glyphicon-refresh-animate"></span> ').prependTo(this);
  $.ajax({
    url: "<?=K_BASE_URL?>/ajax/orderday/readyMail/?id=<?=$orderday->id?>", 
    success: function(data) {
      if (data["result"] != "success") {
        $("#divMain").prepend("<div class='alert alert-danger'><?="Fehler beim Senden"?> (" + data["error"] + ").</div>");
      } else {
        $("#divMain").prepend("<div class='alert alert-success'><?="E-Mails gesendet."?></div>");
        $("#btnOrderReady").hide();
      }
    },
    error: function(xhr, status, error) {
      $("#divMain").prepend("<div class='alert alert-danger'><?=_("Fehler beim Senden")?> (" + error + ").</div>");
    }
  });
});
</script>
