<div class="container">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3>Bestellungen <?=strftime("%x %X", $orderday->time)?></h3>
      <div class="row">
        <label class="col-sm-2 col-xs-4 control-label">Organisator:</label>
        <div class="col-sm-4 col-xs-8"><?=htmlspecialchars($orderday->getOrganizer()->name)?></div>
        <div class="clearfix visible-xs-block"></div>
        <label class="col-sm-2 col-xs-4 control-label">Lieferdienst:</label>
        <div class="col-sm-4 col-xs-8"><?=htmlspecialchars($orderday->deliveryservice)?></div>
      </div>
    </div>
    <div class="panel-body">
      <ul class="list-group">
<?php 
      $ownOrder = false;
      foreach ($orders as $order) {
        if ($order->getUser()->id == $_SESSION['user']->id) {
          $ownOrder = true;
          $editLink = sprintf('<a href="%s/order/edit/?id=%d"><span class="glyphicon glyphicon-pencil"></span></a>',
            $baseUrl,
            $order->id);
        } else {
          $editLink = '';
        }
        printf('<li class="list-group-item"><label>%s</label>: %s <i>%s</i><span class="badge">%.2f €</span>%s</li>',
          htmlspecialchars($order->getUser()->name),
          htmlspecialchars($order->product),
          !empty($order->comment) ? '('.htmlspecialchars($order->comment).')' : '',
          $order->price,
          $editLink);
      }
      if (!$ownOrder) {
        printf('<li class="list-group-item"><a href="%s/order/edit/?day=%d" class="btn btn-primary">Neu</a></li>',
          $baseUrl,
          $orderday->id);
      }
?>
      </ul>
    </div>
  </div>
  
</div>
