<div class="container">
<h1><?= K_PRODUCT_NAME ?></h1>

<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Bestellungen</h3>
  </div>
  <div class="panel-body">
<?php if (!empty($orders)): ?>
    Es gibt aktuell folgende gemeinsame Bestellungen:
    <ul>
<?php foreach ($orders as $order): ?>
      <li>
        <a href="<?=K_BASE_URL?>/orderday/view/?id=<?=$order->id?>">
          <?= strftime("%x %X", $order->time) ?> - <?= htmlspecialchars($order->deliveryservice) ?>
        </a>
      </li>
<?php endforeach; ?>
    </ul>
<?php else: ?>
    <p>Es gibt zur Zeit keine offenen <a href="<?= K_BASE_URL ?>/orderday">Bestellungen</a>.</p>
<?php endif; ?>
  </div>
</div>

<?php if (!empty($debts)): ?>
<div class="panel panel-primary">
  <div class="panel-heading">
    <h3 class="panel-title">Offene Beträge</h3>
  </div>
  <div class="panel-body">
    Folgende Beträge stehen noch aus (positiv: Guthaben, negativ: Schulden beim anderen Benutzer):
    <ul>
<?php 
      foreach ($debts as $debt) {
        echo('<li>');
        printf('%s: <span %s>%.2f €</span>',
          htmlspecialchars($debt['name']),
          $debt['amount']<0 ? 'class="negative"' : '',
          $debt['amount']);
        if ($debt['amount'] < 0 && $debt['paypal'] !== null)
          printf(' <a href="https://paypal.me/%s/%s" title="per PayPal bezahlen">'.
                  '<img src="https://www.paypalobjects.com/webstatic/de_DE/i/de-pp-logo-100px.png" alt="PayPal Logo" style="height:20px"></a>', 
            $debt['paypal'],
            number_format(-$debt['amount'], 2, '.', ''));
        echo('</li>');
      }
?>
    </ul>
  </div>
</div>
<?php endif; ?>

</div>
