<style>
.login {
  background:white;
  padding:25px 40px 25px 40px;
  margin-top:15px;
  box-shadow:0 0 10px grey;
  max-width: 330px;
  margin: 0 auto;
}
.login .form-control {
  margin-bottom:12px;
}
</style>

<?php
if (isset($successMessage)) {
  printf('<div class="alert alert-success">%s</div>', $successMessage);
  // Rest der Seite nicht mehr anzeigen
  echo("</div>");
  return;
} else if (!empty($errorMessage)) {
  printf('<div class="alert alert-danger">%s</div>', $errorMessage);
}
?>
<form class="login collapse in" id="frmLogin" action="<?=K_BASE_URL?>/index/login" method="post">
  <h1>Anmelden</h1>
  <input type="email" class="form-control" placeholder="E-Mail" name="account" autofocus>
  <input type="password" class="form-control" placeholder="Passwort" name="password">
  <button type="submit" class="btn btn-primary form-control">Anmelden</button>
  
  <h3>Noch keinen Zugang?</h3>
  <a href="#" data-toggle="collapse" data-target="#frmLogin,#frmRegister">Hier registrieren</a>.
</form>
<form class="login collapse" id="frmRegister" action="<?=K_BASE_URL?>/index/login" method="post">
  <h1>Registrieren</h1>
  <input type="text" class="form-control" placeholder="Name" name="regName" required>
  <input type="email" class="form-control" placeholder="E-Mail" name="regEmail" required>
  <button type="submit" class="btn btn-primary form-control">Registrieren</button>
</form>

<script>
$("#frmRegister").on("shown.bs.collapse", function(e) {
  $("input[name='regName']").focus();
});
<?php if (!empty($showRegForm)) : ?>
$(function() {$("#frmRegister,#frmLogin").collapse("toggle"); });
<?php endif; ?>
</script>
