<div class="container">

<?php
if (isset($errorMessage)) {
  printf('<div class="alert alert-danger">%s</div>', htmlspecialchars($errorMessage));
}

switch ($step):
  case 1:  // Schritt 1: Link "Passwort vergessen" wurde aufgerufen
?>
  <h3><?=_("Passwort vergessen")?></h3>
  <form action="<?=K_BASE_URL?>/index/resetPassword" method="post" class="form-horizontal">
    <p><?=_("Falls Sie Ihr Passwort vergessen haben, können Sie dieses zurücksetzen. Dazu wird Ihnen eine E-Mail mit den entsprechenden
    Anweisungen zugesendet.")?></p>
    <div class="form-group row">
      <label class="col-sm-3 control-label"><?=_("E-Mail")?>:</label>
      <div class="col-sm-5"><input type="email" name="email" class="form-control" required autofocus></div>
    </div>
    <div class="form-group row">
      <div class="col-sm-4 col-sm-offset-3"><button type="submit" class="btn btn-primary"><?=_("Senden")?></button></div>
    </div>
  </form>

<?php
  break;
  case 2:  // Schritt 2: E-Mail wurde angefordert
?>
  <div class="alert alert-success"><?=_("E-Mail für Passwort-Reset wird zugesandt.")?></div>

<?php
  break;
  case 3:  // Schritt 3: E-Mail-Link wurde aufgerufen
?>
  <h3><?=_("Passwort zurücksetzen")?></h3>
  <p><?=_("Sie können nun Ihr Passwort ändern. Das alte Passwort verliert dadurch seine Gültigkeit.")?>
  <form action="<?=K_BASE_URL?>/index/resetPassword" method="post" class="form-horizontal">
    <input type="hidden" name="token" value="<?=$token?>">
    <div class="form-group row">
      <label class="col-sm-3 control-label"><?=_("Passwort")?>:</label>
      <div class="col-sm-6"><input type="password" name="password" class="form-control" required autofocus minlength="<?=K_MIN_PASSWORD_LEN?>"></div>
    </div>
    <div class="form-group row">
      <label class="col-sm-3 control-label"><?=_("Passwort bestätigen")?>:</label>
      <div class="col-sm-6"><input type="password" name="password2" class="form-control" required></div>
    </div>
    <div class="form-group row">
      <div class="col-sm-4 col-sm-offset-3"><button type="submit" class="btn btn-primary"><?=_("Speichern")?></button></div>
    </div>
  </form>

<?php
  break;
  case 4:  // Schritt 4: neues Passwort wurde eingegeben
?>
<div class="alert alert-success"><?=_("Passwort wurde geändert.")?></div>
<script>setTimeout(function(){ window.location="<?=K_BASE_URL?>"; }, 1000);</script>

<?php 
endswitch;
?>

</div>
