<div class="container">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3>Bestellung für <?=strftime("%x %X", $orderday->time)?></h3>
      <div class="row">
        <label class="col-sm-2 col-xs-4 control-label">Lieferdienst:</label>
        <div class="col-sm-4 col-xs-8">
          <?php if (!empty($orderday->url))
            printf('<a href="%s" target="_blank">%s</a>', $orderday->url, htmlspecialchars($orderday->deliveryservice));
          else
            echo(htmlspecialchars($orderday->deliveryservice));
          ?>
        </div>
      </div>
    </div>
    <div class="panel-body">
      <form class="form-horizontal" action="<?=K_BASE_URL?>/order/edit" method="post">
        <input type="hidden" name="day" value="<?=$orderday->id?>">
        <input type="hidden" name="order" value="<?=isset($order) ? $order->id : ''?>">
        <div class="form-group row">
          <label class="col-sm-3 control-label">Gericht:</label>
          <div class="col-sm-9"><input type="text" class="form-control" name="product" value="<?=isset($order) ? htmlspecialchars($order->product) : ''?>" required autofocus></div>
        </div>
        <div class="form-group row">
          <label class="col-sm-3 control-label">Zusatz:</label>
          <div class="col-sm-9"><input type="text" class="form-control" name="comment" value="<?=isset($order) ? htmlspecialchars($order->comment) : ''?>"></div>
        </div>
        <div class="form-group row">
          <label class="col-sm-3 control-label">Preis:</label>
          <div class="col-sm-3 col-md-2">
            <div class="input-group">
              <input type="number" min="0.01" step="0.01" max="100" class="form-control" name="price" value="<?=isset($order) ? $order->price : ''?>" required>
              <span class="input-group-addon">€</label>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-sm-3 col-sm-offset-3"><button type="submit" class="btn btn-primary">Bestellen</button></div>
        </div>
      </form>
    </div>
  </div>
</div>
