<div class="container">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3>Bestellung für <?=strftime("%x %X", $orderday->time)?></h3>
    </div>
    <div class="panel-body">
      <form class="form-horizontal" action="<?=$baseUrl?>/order/edit" method="post">
        <input type="hidden" name="day" value="<?=$orderday->id?>">
        <input type="hidden" name="order" value="<?=isset($order) ? $order->id : ''?>">
        <div class="form-group row">
          <label class="col-sm-3 control-label">Gericht:</label>
          <div class="col-sm-6"><input type="text" class="form-control" name="product" value="<?=isset($order) ? htmlspecialchars($order->product) : ''?>" required></div>
        </div>
        <div class="form-group row">
          <label class="col-sm-3 control-label">Zusatz:</label>
          <div class="col-sm-6"><input type="text" class="form-control" name="comment" value="<?=isset($order) ? htmlspecialchars($order->comment) : ''?>"></div>
        </div>
        <div class="form-group row">
          <label class="col-sm-3 control-label">Preis:</label>
          <div class="col-sm-2"><input type="number" min="0.01" step="0.01" max="100" class="form-control" name="price" value="<?=isset($order) ? $order->price : ''?>" required></div>
          <label class="col-sm-1 control-label">€</label>
        </div>
        <div class="row">
          <div class="col-sm-3 col-sm-offset-3"><button type="submit" class="btn btn-primary">Bestellen</button></div>
        </div>
      </form>
    </div>
  </div>
</div>
