<div class="container">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3>Bestellung für <?=strftime("%x %X", $orderday->time)?></h3>
      <div class="row">
        <label class="col-sm-2 col-xs-4 control-label">Lieferdienst:</label>
        <div class="col-sm-4 col-xs-8">
          <?php if (!empty($orderday->url))
            printf('<a href="%s" target="_blank">%s</a>', $orderday->url, htmlspecialchars($orderday->deliveryservice));
          else
            echo(htmlspecialchars($orderday->deliveryservice));
          ?>
        </div>
      </div>
    </div>
    <div class="panel-body">
      <form class="form-horizontal" action="<?=K_BASE_URL?>/order/edit" method="post">
        <input type="hidden" name="day" value="<?=$orderday->id?>">
        <input type="hidden" name="order" value="<?=isset($order) ? $order->id : ''?>">
        <div class="form-group row">
          <label class="col-sm-3 control-label">Gericht:</label>
          <div class="col-sm-9"><input type="text" class="form-control" name="product" value="<?=isset($order) ? htmlspecialchars($order->product) : ''?>" required autofocus></div>
        </div>
        <div class="form-group row">
          <label class="col-sm-3 control-label">Zusatz:</label>
          <div class="col-sm-9"><input type="text" class="form-control" name="comment" value="<?=isset($order) ? htmlspecialchars($order->comment) : ''?>"></div>
        </div>
        <div class="form-group row">
          <label class="col-sm-3 control-label">Preis:</label>
          <div class="col-sm-3 col-md-2">
            <div class="input-group">
              <input type="number" min="0.01" step="0.01" max="100" class="form-control" name="price" value="<?=isset($order) ? $order->price : ''?>" required>
              <span class="input-group-addon">€</label>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-sm-9 col-sm-offset-3">
<?php       if (isset($order)): ?>
              <button type="submit" class="btn btn-primary">Speichern</button>
              <button type="submit" class="btn btn-default" name="delete" value="t">Löschen</button>
<?php else: ?>
              <button type="submit" class="btn btn-primary">Bestellen</button>
<?php       endif; 
            if (!empty($menuitems)): ?>
              <button type="button" class="btn btn-default" id="btnMenu">Speisekarte</button>
<?php       endif;
            if (!empty($ownFavourites) || !empty($allFavourites)): ?>
              <button type="button" class="btn btn-default" id="btnRecommend">Empfehlungen</button>
<?php       endif; ?>
            
          </div>
        </div>
      </form>
    </div>
  </div>
</div>

<?php
if (!empty($menuitems)): ?>
<div id="modalMenu" class="modal fade" role="dialog" tabindex="-1">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header panel-heading">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Speisekarte</h4>
      </div>
      <div class="modal-body">
        <table class="table table-striped">
<?php   foreach ($menuitems as $menuitem) {
          printf('<tr role="button"><td>%s</td><td>%s</td></tr>', 
            htmlspecialchars($menuitem->name), 
            htmlspecialchars($menuitem->price));
        } ?>
        </table>
      </div>
<!--      <div class="modal-footer">
      </div> -->
    </div>
  </div>
</div>
<script>
$('#btnMenu').click(function(e) {
  $('#modalMenu').modal();
});
$('#modalMenu').on('click', 'tr', function(e) {
  $('#modalMenu').modal('hide');
  $('input[name="product"]').val($(this).find("td:first").text());
  $('input[name="price"]').val(parseFloat($(this).find("td:nth-child(2)").text().replace(",", ".")));
});
</script>
<?php
endif; 

if (!empty($ownFavourites) || !empty($allFavourites)): ?>

<div id="modalRecommendations" class="modal fade" role="dialog" tabindex="-1">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header panel-heading">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Favoriten</h4>
      </div>
      <div class="modal-body">
        <h4>Eigene Favoriten</h4>
        <table class="table table-striped">
<?php   foreach ($ownFavourites as $fav) {
          printf('<tr role="button"><td>%s</td><td>%s</td></tr>', 
            htmlspecialchars($fav->product), 
            htmlspecialchars($fav->price));
        } ?>
        </table>
        <h4>Favoriten aller Mitbesteller</h4>
        <table class="table table-striped">
<?php   foreach ($allFavourites as $fav) {
          printf('<tr role="button"><td>%s</td><td>%s</td></tr>', 
            htmlspecialchars($fav->product), 
            htmlspecialchars($fav->price));
        } ?>
        </table>
      </div>
<!--      <div class="modal-footer">
      </div> -->
    </div>
  </div>
</div>
<script>
$('#btnRecommend').click(function(e) {
  $('#modalRecommendations').modal();
});
$('#modalRecommendations').on('click', 'tr', function(e) {
  $('#modalRecommendations').modal('hide');
  $('input[name="product"]').val($(this).find("td:first").text());
  $('input[name="price"]').val(parseFloat($(this).find("td:nth-child(2)").text().replace(",", ".")));
});
</script>

<?php
endif; ?>

<script>
$(":submit[name='delete']").click(function(e) {
  return confirm("Wirklich löschen?");
});
</script>
